use_frameworks!

platform :ios, '9.0'

target 'DRScrollableViews_Example' do
  pod 'DRScrollableViews', :path => '../'
  pod 'HexColors', '~> 4.0.0'

  target 'DRScrollableViews_Tests' do
    inherit! :search_paths

    
  end
end
